#LOG_ENABLED=False

NEWSPIDER_MODULE = "projectfiles.spiders"
SPIDER_MODULES = "projectfiles.spiders"

EXTENSIONS = {
   'scrapy.telnet.TelnetConsole': None
}

AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 0
AUTOTHROTTLE_MAX_DELAY = 15
CONCURRENT_REQUESTS = 8

DOWNLOAD_TIMEOUT = 1200
DOWNLOAD_MAXSIZE = 0
DOWNLOAD_WARNSIZE = 0

ROBOTSTXT_OBEY = False
USER_AGENT = ""

